USE [master]
GO

/****** Object:  Database [CovidDB]    Script Date: 23/10/2022 18:12:34 ******/
CREATE DATABASE [CovidDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CovidDB', FILENAME = N'C:\Users\User\CovidDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CovidDB_log', FILENAME = N'C:\Users\User\CovidDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CovidDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CovidDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CovidDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CovidDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CovidDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CovidDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CovidDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CovidDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CovidDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CovidDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CovidDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CovidDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CovidDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CovidDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CovidDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CovidDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CovidDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CovidDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CovidDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CovidDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CovidDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CovidDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CovidDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CovidDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CovidDB] SET  MULTI_USER 
GO

ALTER DATABASE [CovidDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CovidDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CovidDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CovidDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CovidDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CovidDB] SET QUERY_STORE = OFF
GO

USE [CovidDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CovidDB] SET  READ_WRITE 
GO


